---
title: "PCA"
author: "Anh Thu"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load the library
```{r}
library(readr)
library(dplyr)
library(plyr)
library(lubridate)
library(ggpubr)
library(tidyr)
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(factoextra)
library(xtable)
library(FactoMineR)
library(cluster.datasets)
```

```{r}
#library(Hmisc)
library(viridis)  
library(naniar)
library(xtable)
#library(schoRsch)
library(gmodels)
library(emmeans)
library(rstatix)
library(multcomp)
library(sandwich)
library(pim)
library(stargazer)
library(survival)
library(survminer)
library(finalfit)
library(ggplot2)
```


```{r}
pca_hiv = read.csv('hiv_pca.csv',quote="")
colnames(pca_hiv)
```
```{r}
head(pca_hiv)
```

```{r}
xtable(anova(lm(Infectionrate~ NewHDI, data = pca_hiv)))
```


```{r}
model <- lm(formula=as.formula(paste(paste("Infectionrate",'~', sep=''),
paste(c("Sex", "NewHDI",'Region'),collapse='+'), sep='')),
            pca_hiv)
xtable(summary(model))
```
```{r}
anova(model)
```







```{r}
df_active <- pca_hiv[,c("AnnualInfection", "Deathrate", "AnnualDeaths","Infectionrate", "LivingHIV","HDI")]
```

```{r}
res.pca <- PCA(df_active, graph= FALSE)
summary(res.pca)
```

```{r}
fviz_pca_ind(res.pca, col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE  # Avoid text overlapping
             )
```

```{r}
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = pca_hiv$NewHDI, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups",
             select.ind = list(contrib=500)
             )
```

```{r}
res.pca = PCA(df_active[,1:5], scale.unit=TRUE, ncp=3, quanti.sup=c(5), graph=T)
```



```{r}
# PCA with function prcomp
pca1 = prcomp(df_active, scale. = TRUE)
# sqrt of eigenvalues
pca1$sdev
```

```{r}
pca1$rotation
```

```{r}
xtable(pca1$rotation)
```

